### ISSUE TITLE
Event page reporting "The field cannot be extended"

### ISSUE THREAD

**Issue by digiltd** [moritzz/Kirby-Calendar#2]
Hi

I am trying to work out your plugin, but I have been unsuccessful.

First I tried installing it within my project and then I installed it on a fresh Kirby starter kit.

I install manually (and then copy over the submodule for iCalcreator). I add a calendar page to the dashboard. When I try to add an event page as a child of the calendar page, I fill in the modal but when i try to add i get the "field cannot be extended" error.

I have also tried the calendar page as a subpage, but that gave the same results.

Any suggestions?

Thanks

**Comment by moritzz** [comment]
Hi @digiltd

Sorry for the inconvenience. Calendar indeed had a bug I did not spot because of my testing setup. I just fixed and tested it. Please make sure to use at least Kirby 2.3.1 (see [Kirby issue #272 common](https://github.com/getkirby/getkirby.com/issues/272#issuecomment-233268643)) for the line `$kirby->set('blueprint', 'fields/events', __DIR__ . '/blueprints/fields/events.yml');` fixing this issue to work.

Thanks for reporting,  
Moritz
